### ISSUE TITLE
Create a StorageSvc or use the Angular Service for it

### ISSUE THREAD

**Issue by AVGP** [MichaelKohler/jabber-firefox-os#21]

**Comment by AVGP** [comment]
At least for the account data, localStorage is sufficient. For history we shall look at IndexDB

**Comment by MichaelKohler** [comment]
There is already a storage.js.. We could use that one and implement IndexDB there.

**Comment by MichaelKohler** [comment]
Well, of course we would need to rewrite it to a Service, but I could do that.

**Comment by MichaelKohler** [comment]
https://github.com/MichaelKohler/jabber-firefox-os/commit/f55688b77fd7c975b020499431751cf209966e70
