### ISSUE TITLE
Create a App Icon 

### ISSUE THREAD

**Issue by SunboX** [MichaelKohler/jabber-firefox-os#33]
I will create a application icon in svg & png by using a stylized Jabber sign (lightbulb) and a message bubble. This should communicate "you can message/chat with this app using Jabber".

**Comment by SunboX** [comment]
Fixed with https://github.com/MichaelKohler/jabber-firefox-os/pull/38

**Comment by AVGP** [comment]
Reeeally nice!

**Comment by SunboX** [comment]
thx, I'm happy you like it.
