### ISSUE TITLE
angular.min.js.map not found exception

### ISSUE THREAD

**Issue by SunboX** [MichaelKohler/jabber-firefox-os#49]
I'm getting this Exception using Chrome:

```
GET http://localhost/jabber-firefox-os/app/scripts/lib/angular.min.js.map 404 (Not Found) /jabber-firefox-os/app/scripts/lib/angular.min.js.map:1
```

**Comment by MichaelKohler** [comment]
might be good to have that if somebody want's to debug it :D

**Comment by SunboX** [comment]
:+1: 

And also un-minified source for development. ;) Even Angular creator says you should use the unminified one when developing. ;) http://www.youtube.com/watch?v=ZhfUv0spHCY&list=TLIzE6p2M99hUZxh0s4xgXvK9Pc-XI4iyx
