### ISSUE TITLE
CORS issue with jabber.ccc.de

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/jabber-firefox-os#69]

**Comment by MichaelKohler** [comment]
when clicking on the "Test Connection" button in the "Account" panel, I get a "Error: CORS request rejected: http://jabber.ccc.de/http-bind"

**Comment by SunboX** [comment]
Maybe this will fix it: http://de.slideshare.net/AniruddhaAdhikary/systemxhr-crossdomain-xmlhttprequests
But that will require a modification of node-xmpp-browser

**Comment by SunboX** [comment]
Oh, it's already set: https://github.com/MichaelKohler/jabber-firefox-os/blob/master/app/scripts/lib/node-xmpp-browser.js#L1475
Maybe we need to add a permission to the manifest file

**Comment by SunboX** [comment]
``` json
"permissions": {
    "systemXHR": { "description": "Required for certain web communications" }
}
```

**Comment by SunboX** [comment]
Hm, it's also already set. :( So, this should work!

**Comment by SunboX** [comment]
But it will only work using a Firefox OS device! Not inside a browser. ;)

**Comment by MichaelKohler** [comment]
oh, of course.. let me verify that :)

**Comment by ghost** [comment]
When i tried to add an account, i could reproduce the "Error: CORS request rejected: http://jabber.ccc.de/http-bind" message only when i try to use the **https** version https://jabber.ccc.de/http-bind

To fix that issue i visit the **https** address with the FirefoxOS browser and add a permanent exception for the self signed certificate.

But after that i see a different error message "Error: Invalid parameters":

![index](https://cloud.githubusercontent.com/assets/4523264/12577047/379fcf86-c418-11e5-8810-1564acdaec32.png)

```
Invalid parameters services.js:66:12
setupDefaultListeners/<() services.js:66
require<[24]</EventEmitter.prototype.emit() node-xmpp-browser.js:2742
require<[24]</EventEmitter.prototype.emit() node-xmpp-browser.js:2742
BOSHConnection/<() node-xmpp-browser.js:777
require<[10]</BOSHConnection.prototype.request/<() node-xmpp-browser.js:906
on_end() node-xmpp-browser.js:1584
on_state_change() node-xmpp-browser.js:1534
```
