### ISSUE TITLE
add Gulp task to get the latest Transifex localizations

### ISSUE THREAD

**Issue by MichaelKohler** [MichaelKohler/jabber-firefox-os#72]

**Comment by SunboX** [comment]
This won't work. We use the new *.l20n files, Transifex doesn't support by now. We have to rewrite them from Mozilla *.properties to *.l20n Maybe I can automate this. Let me check.

**Comment by SunboX** [comment]
There's a Gulp Transifex Plugin here: https://github.com/NEURS/gulp-transifex we "just" have to pipe the response to a "PropertiesToL20nConverter" that has to be created.

**Comment by SunboX** [comment]
Nearly done with PR https://github.com/MichaelKohler/jabber-firefox-os/commit/0da65f861a89c85abcd451f188345e522ad8bac5
Forgot to automatically update https://github.com/MichaelKohler/jabber-firefox-os/blob/master/app/locales/jabber.json
PR will follow.

**Comment by SunboX** [comment]
Fixed with https://github.com/MichaelKohler/jabber-firefox-os/commit/71176995a6f924ed6a9acb9ec34d3bd2fd2aa121
